// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/igaming-landing/Advertisers.tsx": () => import("../components/mockups/igaming-landing/Advertisers.tsx"),
  "./components/mockups/igaming-landing/Affiliates.tsx": () => import("../components/mockups/igaming-landing/Affiliates.tsx"),
  "./components/mockups/igaming-landing/Aggressive.tsx": () => import("../components/mockups/igaming-landing/Aggressive.tsx"),
  "./components/mockups/igaming-landing/DarkStudioBlue.tsx": () => import("../components/mockups/igaming-landing/DarkStudioBlue.tsx"),
  "./components/mockups/templates/BlueCoworkingLanding-T15Ydg/Atrium.tsx": () => import("../components/mockups/templates/BlueCoworkingLanding-T15Ydg/Atrium.tsx"),
  "./components/mockups/templates/CinematicFilmTeaserPost-T3tqRc/GlassHoursPromo.tsx": () => import("../components/mockups/templates/CinematicFilmTeaserPost-T3tqRc/GlassHoursPromo.tsx"),
  "./components/mockups/templates/ColossalTypographicLanding-XL0mx8/Northbound.tsx": () => import("../components/mockups/templates/ColossalTypographicLanding-XL0mx8/Northbound.tsx"),
  "./components/mockups/templates/DarkAthleticCoachingLandingPage-X77PG0/Lp03.tsx": () => import("../components/mockups/templates/DarkAthleticCoachingLandingPage-X77PG0/Lp03.tsx"),
  "./components/mockups/templates/DarkLuxuryTravelLandingPage-t4cr_C/Lp06.tsx": () => import("../components/mockups/templates/DarkLuxuryTravelLandingPage-t4cr_C/Lp06.tsx"),
  "./components/mockups/templates/DarkStudioComingSoonPost-2Bgw0-/ComingSoon.tsx": () => import("../components/mockups/templates/DarkStudioComingSoonPost-2Bgw0-/ComingSoon.tsx"),
  "./components/mockups/templates/DarkTypographicStudioPoster-JfGD1l/StudioLogo.tsx": () => import("../components/mockups/templates/DarkTypographicStudioPoster-JfGD1l/StudioLogo.tsx"),
  "./components/mockups/templates/EditorialDeFiMilestoneEmail-DN94NW/App.tsx": () => import("../components/mockups/templates/EditorialDeFiMilestoneEmail-DN94NW/App.tsx"),
  "./components/mockups/templates/NeonWorkoutSupportLandingPage-igjiuS/App.tsx": () => import("../components/mockups/templates/NeonWorkoutSupportLandingPage-igjiuS/App.tsx"),
  "./components/mockups/templates/WabiSabiSkincarePost-6AkvsO/App.tsx": () => import("../components/mockups/templates/WabiSabiSkincarePost-6AkvsO/App.tsx"),
  "./components/mockups/templates/WabiSabiSkincarePost-aBRe1X/App.tsx": () => import("../components/mockups/templates/WabiSabiSkincarePost-aBRe1X/App.tsx")
};
